//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_mvvm_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        

        public int Book_ID { get; set; }
        public string Author { get; set; }
        public string Title { get; set; }           
        public int Year { get; set; }
        public string TopicCBList { get; set; }
    }
}
